# -*- coding: utf-8 -*-
"""CustomerGrouping

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZaaqRoomUXA3ovoeyDNFYM2SHWRNFn3k
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import files
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd

# %matplotlib inline

uploaded = files.upload()

# Get the first key from the uploaded dictionary
file_name = list(uploaded.keys())[0]

# Read the CSV file into a DataFrame
CustGroup = pd.read_csv(file_name)

# Display the first few rows of the DataFrame
print(CustGroup.head())

nRowsRead = 1000 # specify 'None' if want to read whole file
df1 = pd.read_csv(file_name, delimiter=',', nrows = nRowsRead)
df1.dataframeName = 'Mall_Customers.csv'
nRow, nCol = df1.shape
print(f'There are {nRow} rows and {nCol} columns')

df1.head(5)

def plotPerColumnDistribution(df, rows, cols):
    df.hist(figsize=(10, 5), bins=20)
    plt.show()

def plotCorrelationMatrix(df, rows, cols):
    df.hist(figsize=(8, 8), bins=20)
    plt.show()

def plotScatterMatrix(df, rows, cols):
    df.hist(figsize=(12, 10), bins=20)
    plt.show()